FROM nginx:latest

COPY index.html /usr/share/nginx/html
COPY favicon.ico /usr/share/nginx/html
COPY Rakefile /usr/share/nginx/html
COPY style/ /usr/share/nginx/html/style/
COPY meta/ /usr/share/nginx/html/meta/
COPY js/ /usr/share/nginx/html/js/

EXPOSE 80

#docker build -t twentyfortyeight .
#docker run -d -p 80:80 twentyfortyeight
